### PR TITLE
fix missing word in readme

### PR DESCRIPTION
**Pull request by nielsswinkels**

### CODE REVIEW

**Comment by fajartimur** [comment]
i have this problem when i was trying to install the required module, i am
using windows 7 OS, if anyone can help me please[image: error.PNG]


Pada tanggal Sel, 8 Okt 2019 pukul 19.19 Niels <notifications@github.com>
menulis:

**Comment by nielsswinkels** [comment]
Hi @fajartimur you are writing this at the wrong place. Please start a new issue here instead: https://github.com/OpenEIT/OpenEIT/issues

**Comment by fajartimur** [comment]
okay Niels, thank you for your reply and help,. really appreciate it,.
already trying your advice, but it is still not working though,. maybe i
have to study and read more about this subject,. i'm still a beginner, but
really interested in this biomedical research. you said that you are using
linux right, is there any issue that you have encountered?,. if not maybe i
need to migrate to linux instead, anyway thanks again for your help

Pada tanggal Jum, 11 Okt 2019 pukul 13.58 Niels <notifications@github.com>
menulis:

**Comment by nielsswinkels** [comment]
I have no idea what you are talking about. You are asking for help in the wrong thread. Start a new thread (called Issue) here https://github.com/OpenEIT/OpenEIT/issues and ask your questions there.

**Review by JeanRintoul — APPROVED** [review]

**Pull request merged**
