### PR TITLE
Major Refactoring

### LINKED ISSUE #1: Incoherent Coding Style
The dashboard code and the supporting modules are incoherently indented, documented and spaced (especially, they violate the recommendations of [PEP 8](https://www.python.org/dev/peps/pep-0008/)). Further the naming of the modules is not friendly for installation.

I propose the following changes:
* use coherent indentation, docstring style and spacing (ideally conforming to PEP8)
* create a package called `OpenEIT` (or `open_eit` to make pep 8 happy)
* move the support modules there and pep8ify their names (e.g. `Serialhandler` => `OpenEIT.serial_handler`)
* add a setup.py  that installs the OpenEIT package

I consider a coherent style highly relevant for the long term success of the project, since coherent style is inviting to contributors and helps with long-term maintainablity.

I'd be happy to do the changes and open a PR with the adapted code, but since it is a quite invasive procedure I wanted to ask for an okay before I started (especially since this will make merging concurrent changes difficult!).

### PR DESCRIPTION
**Pull request by sebastianriese**
This should fix #1 and #3.

The modules `Reconstruction` and `Serialhander` have been restructured to live in the `OpenEIT` package.

I could not test with hardware, but I implemented an emulation mode that feeds the data through a PTY, which allows to feed recorded data through the serial-handler code as if it would be coming from a serial connection.

This PR also implements some parallelization of data-input, processing and rendering via threads (note: this might not allow to fully use several cores due to the python global interpreter lock, but at least numpy releases the GIL during math operations).

Porting the code to use multiprocessing instead of threading for the reconstruction worker process should be straightforward (but comes with some restrictions due to the way multiprocessing works).

The interface of the dashboard controller is still somewhat preliminary, but should allow easy adaption to a front-end using a more complete GUI toolkit (e.g. Qt) in place of tkinter.

### CODE REVIEW

**Review by JeanRintoul — CHANGES_REQUESTED** [review]
Thanks for doing this, though I currently cannot run it unless I move matplotlib.use("TkAgg") in dashboard.py above pyplot import statement. I'm about to test it further and with device.

**Review by JeanRintoul — APPROVED** [review]

**Comment by JeanRintoul** [comment]
[anticlockwise_motion.txt](https://github.com/OpenEIT/EIT_Dashboard/files/1613279/anticlockwise_motion.txt)

Refactoring Notes: 

Above I've attached a binary file of anticlockwise motion. To use it, please rename the extension to .bin as github doesnt let you upload .bin's so I changed it. This should be useful in resolving any of the errors listed. 

1. These imports in dashboard.py must be in the following order otherwise it doesn't start up:
import matplotlib
matplotlib.use("TkAgg")
import matplotlib.pyplot as mpl

2. It no longer throws an error when the wrong data comes out of the serial port. I ran some different firmware and no error was thrown. 

3. Is there a buffer size of unrendered images? What happened to this update to text that appeared in the gui: time render, time math,  byte buffer size?
Byte buffer size(data stored waiting to be rendered) is useful to see in cases it starts collecting. i.e. when it opens the second 'dedicated reconstruction window'.  

4. Reset file marker button doesn't seem to work or allow you to run the file again. Step back button also doesn't work. After the file has been read in and run through once, none of the file reading button work again as if some variable is not being reset properly. 

5. To recreate reconstruction error, I read in anticlockwise.bin, and ran it and it gets this error at the end. 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/jeanrintoul/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/jeanrintoul/Desktop/mindseyebiomedical/OpenEIT/EIT_Dash_pull/EIT_Dashboard/OpenEIT/reconstruction/radon.py", line 47, in run
    img = self._reconstruction.eit_reconstruction(data)
  File "/Users/jeanrintoul/Desktop/mindseyebiomedical/OpenEIT/EIT_Dash_pull/EIT_Dashboard/OpenEIT/reconstruction/radon.py", line 187, in eit_reconstruction
    d, deg = self.makeimages(data)
  File "/Users/jeanrintoul/Desktop/mindseyebiomedical/OpenEIT/EIT_Dash_pull/EIT_Dashboard/OpenEIT/reconstruction/radon.py", line 87, in makeimages
    "the datasets must match the logfile specification"
ValueError: the datasets must match the logfile specification

**Comment by sebastianriese** [comment]
Sorry for breaking it (obviously, it works for me). I will try to fix the issues. What versions of Python and matplotlib are you using? I ask because some of the problems do not occur in my setup and may be due to changes between versions.

My notes on the annotations:

1. I noted, that I needed to import matplotlib things from different subpackages than the original code did – so a matplotlib version mismatch could also explain the problems with the order of the matplotlib imports. (Probably, I should set up a testing environment, where I have access to the different matplotlib versions for testing; my native environment has Python 3.5.5 and matplotlib 2.0.0).

2. That should definitely be fixed, but a proper solution is difficult: The matching firmware will first send some start-up information and then begin to send measurement data. So the application cannot know whether there is an error unless it were to check for the specific start-up sequence. The data from another firmware would simply be discarded as invalid data.

3. All data received from the hardware/file is sent to the input queue, where it is buffered until it is read by the processing thread, which renders the image (currently there is only one render-worker, so only one image is rendered at a time, even if more CPU cores and data would be available). Then the rendered image is enqueued in the render queue and rendered as soon as the main thread has time for that. Currently there is actually no limit on the number of measurements to be queued, this is probably not too problematic but could lead to memory exhaustion when the program is long running. (Especially, if rendering does not keep up with the data input). The render time is now only written in
the application log (when starting the dashboard from the terminal it should be printed there) and not accumulated, if you consider the display of that information important I will add it again.

4. Will be fixed (I tested the serial port emulation feature more, so it is quite possible I missed a bug in the direct file replay).

5. I will test with that datafile (and improve the error handling to try to display errors in the GUI). All the files that I tried from the directories `datasets` and `reconstruction_tests/datasets` worked (in my setup).

**Comment by JeanRintoul** [comment]
1. Understood - That native environment is the difference. This is tricky and why I thought using Anaconda would be the right move to make installation simpler. Anaconda installs all compatible numerical libraries together to make installation ideally more simple. 
https://www.anaconda.com/download/#macos was for me, though you can also get it for Linux or Windows with same package configurations. 
Python 3.6.3 :: Anaconda, Inc.
This list on this page tells you the versions of every library: https://docs.anaconda.com/anaconda/packages/py3.6_osx-64
I did have to install pyserial however(conda install pyserial), which is Version: 3.4. 

2. Agree, perhaps this can be addressed once I release a board(with firmware) which I've started over here but not finished. 

3. The debug log is a good place for it if rendering time is no longer a limiting factor. If it's still a problem it's handy to see it. I had it displayed as I could see the accumulation of the buffer occur when various GUI actions were performed and it was useful to see where pressing a button, or moving a slider, caused things to slow.  

4. Yeah, I think this is an easy fix just some variable not reset after it is run once. 

5. Ok great. Once your changes are merged back in I'll upload some more datafiles to the repository. 

Also, see my added commentary to the OpenGL solution, I'm wondering how it could be implemented in a way that doesn't make installation very tricky. It'd be great if this main tool was easily accessible to people without too much trouble, but hackable at a high level once they got into it.

**Pull request merged**
